# Base Image
BOX_IMAGE = "ubuntu/focal64"
BOX_VERSION = "20211004.0.0"

# max number of worker nodes
N = 2

Vagrant.configure("2") do |config|
#-----Manager Node
    config.vm.define "k8s-cilium-m" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      config.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.name = "k8s-cilium-m"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-m"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.200.10"
      subconfig.vm.network "forwarded_port", guest: 22, host: 51010, auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "init_cfg.sh", args: N
      #subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/DKOS/main/2/init_cfg.sh", args: N
      subconfig.vm.provision "shell", path: "master.sh"
      #subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/DKOS/main/2/master.sh"
    end

#-----Worker Node
  (1..N).each do |i|
    config.vm.define "k8s-cilium-w#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      config.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.name = "k8s-cilium-w#{i}"
        v.memory = 1536
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-w#{i}"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.200.10#{i}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "5101#{i}", auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "init_cfg.sh", args: N
      #subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/DKOS/main/2/init_cfg.sh", args: N
      subconfig.vm.provision "shell", path: "worker.sh"
      #subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/DKOS/main/2/worker.sh"
    end
  end

end
