apiVersion: v1
kind: Pod
metadata:
  name: myweb
spec:
  containers:
  - image: nginx
    name: myweb
    ports:
    - containerPort: 80
      protocol: TCP
  terminationGracePeriodSeconds: 0
  nodeSelector:
    gpu: ndivia