# Base Image
BOX_IMAGE = "ubuntu/focal64"
BOX_VERSION = "20211026.0.0"

# max number of Add master nodes
M = 2

# max number of worker nodes
N = 1

Vagrant.configure("2") do |config|
#-----Manager Node 0
    config.vm.define "k8s-m0" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/K8S-HA-Lab"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        v.name = "HA-k8s-m0"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-m0"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.100.10"
      subconfig.vm.network "forwarded_port", guest: 22, host: "50010", auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/NDKS/main/HA-K8S/init_cfg.sh", args: [M, N]
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/NDKS/main/HA-K8S/master.sh", args: M
    end

#-----Add Manager Node
  (1..M).each do |m|
    config.vm.define "k8s-m#{m}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/K8S-HA-Lab"]
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        v.name = "HA-k8s-m#{m}"
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-m#{m}"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.100.1#{m}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "5001#{m}", auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/NDKS/main/HA-K8S/init_cfg.sh", args: [M, N]
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/NDKS/main/HA-K8S/master_join.sh", args: M
    end
  end

#-----Worker Node
  (1..N).each do |n|
    config.vm.define "k8s-w#{n}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--groups", "/K8S-HA-Lab"]
        v.name = "HA-k8s-w#{n}"
        v.memory = 1024
        v.cpus = 1
        v.linked_clone = true
      end
      subconfig.vm.hostname = "k8s-w#{n}"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.network "private_network", ip: "192.168.100.10#{n}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "5011#{n}", auto_correct: true, id: "ssh"
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/NDKS/main/HA-K8S/init_cfg.sh", args: [M, N]
      subconfig.vm.provision "shell", path: "https://raw.githubusercontent.com/gasida/NDKS/main/HA-K8S/worker.sh"
    end
  end
end